const express=require('express');const path=require('path');const jwt=require('jsonwebtoken');const bcrypt=require('bcryptjs');const Database=require('better-sqlite3');
const app=express();app.use(express.json({limit:'10mb'}));app.use(express.static(path.join(__dirname,'public')));
const db=new Database(path.join(__dirname,'data','savoury.db'));const SECRET=process.env.SAVOURY_SECRET||'CHANGE_THIS_SECRET_IN_PRODUCTION';
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,employee_no TEXT UNIQUE,username TEXT UNIQUE,name TEXT,password_hash TEXT,role TEXT,department TEXT,site TEXT,status TEXT DEFAULT 'active');
CREATE TABLE IF NOT EXISTS employees(id INTEGER PRIMARY KEY AUTOINCREMENT,employee_no TEXT UNIQUE,name TEXT,department TEXT,position TEXT,site TEXT,salary REAL DEFAULT 0,status TEXT DEFAULT 'active');
CREATE TABLE IF NOT EXISTS inventory(id INTEGER PRIMARY KEY AUTOINCREMENT,sku TEXT UNIQUE,item TEXT,site TEXT,qty REAL DEFAULT 0,min_qty REAL DEFAULT 0,unit TEXT);
CREATE TABLE IF NOT EXISTS sales(id INTEGER PRIMARY KEY AUTOINCREMENT,order_no TEXT UNIQUE,site TEXT,total REAL DEFAULT 0,payment TEXT,date TEXT);
CREATE TABLE IF NOT EXISTS purchases(id INTEGER PRIMARY KEY AUTOINCREMENT,ref_no TEXT UNIQUE,site TEXT,total REAL DEFAULT 0,supplier TEXT,date TEXT);
CREATE TABLE IF NOT EXISTS content(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT,title TEXT,body TEXT,status TEXT DEFAULT 'draft',scope TEXT DEFAULT 'public',created_at TEXT);
CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT,body TEXT,target TEXT,created_at TEXT);
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT,action TEXT,entity TEXT,entity_id TEXT,created_at TEXT);`);
const count=db.prepare('SELECT COUNT(*) c FROM users').get().c;if(!count){const h=bcrypt.hashSync('admin123',10);db.prepare('INSERT INTO users(employee_no,username,name,password_hash,role,department,site) VALUES(?,?,?,?,?,?,?)').run('0001','admin','SAVOURY Owner',h,'owner','Management','ALL');}
function auth(req,res,next){try{const t=(req.headers.authorization||'').replace('Bearer ','');req.user=jwt.verify(t,SECRET);if(req.user.status!=='active')return res.status(403).json({error:'Account inactive'});next()}catch(e){res.status(401).json({error:'Unauthorized'})}}
function audit(u,a,e,id){db.prepare('INSERT INTO audit(username,action,entity,entity_id,created_at) VALUES(?,?,?,?,datetime(\'now\'))').run(u,a,e,String(id||''));}
app.post('/api/login',(req,res)=>{const {username,password}=req.body;const u=db.prepare('SELECT * FROM users WHERE username=? OR employee_no=?').get(username,username);if(!u||u.status!=='active'||!bcrypt.compareSync(password||'',u.password_hash))return res.status(401).json({error:'بيانات الدخول غير صحيحة'});const token=jwt.sign({id:u.id,username:u.username,name:u.name,role:u.role,department:u.department,site:u.site,status:u.status},SECRET,{expiresIn:'8h'});audit(u.username,'login','user',u.id);res.json({token,user:{id:u.id,employee_no:u.employee_no,username:u.username,name:u.name,role:u.role,department:u.department,site:u.site,status:u.status}})});
app.get('/api/me',auth,(req,res)=>res.json(req.user));
app.get('/api/dashboard',auth,(req,res)=>{const sales=db.prepare('SELECT COALESCE(SUM(total),0) total FROM sales WHERE date(date)=date(\'now\')').get().total;const emp=db.prepare('SELECT COUNT(*) c FROM employees WHERE status=\'active\'').get().c;const low=db.prepare('SELECT COUNT(*) c FROM inventory WHERE qty<=min_qty').get().c;const content=db.prepare('SELECT COUNT(*) c FROM content WHERE status=\'published\'').get().c;res.json({sales,employees:emp,lowStock:low,publishedContent:content,role:req.user.role,site:req.user.site})});
const tables={employees:'employees',inventory:'inventory',sales:'sales',purchases:'purchases',content:'content',notifications:'notifications',audit:'audit',users:'users'};
app.get('/api/:entity',auth,(req,res)=>{const t=tables[req.params.entity];if(!t)return res.status(404).json({error:'Not found'});if(t==='audit'&&req.user.role!=='owner')return res.status(403).json({error:'Forbidden'});res.json(db.prepare(`SELECT * FROM ${t} ORDER BY id DESC LIMIT 500`).all())});
app.post('/api/:entity',auth,(req,res)=>{const t=tables[req.params.entity];if(!t||t==='audit'||t==='users')return res.status(403).json({error:'Not allowed'});const allowed={employees:['employee_no','name','department','position','site','salary','status'],inventory:['sku','item','site','qty','min_qty','unit'],sales:['order_no','site','total','payment','date'],purchases:['ref_no','site','total','supplier','date'],content:['type','title','body','status','scope'],notifications:['title','body','target']}[t];const data={};allowed.forEach(k=>{if(req.body[k]!==undefined)data[k]=req.body[k]});if(t==='content'&&!data.status)data.status='draft';if(t==='content'&&!data.scope)data.scope='public';if(!Object.keys(data).length)return res.status(400).json({error:'No data'});const keys=Object.keys(data),vals=keys.map(k=>data[k]);try{const r=db.prepare(`INSERT INTO ${t}(${keys.join(',')}) VALUES(${keys.map(()=>'?').join(',')})`).run(...vals);audit(req.user.username,'create',t,r.lastInsertRowid);res.json({id:r.lastInsertRowid})}catch(e){res.status(400).json({error:e.message})}});
app.patch('/api/:entity/:id',auth,(req,res)=>{const t=tables[req.params.entity];if(!t||t==='audit')return res.status(403).json({error:'Not allowed'});const allowed={employees:['name','department','position','site','salary','status'],inventory:['item','site','qty','min_qty','unit'],content:['type','title','body','status','scope'],notifications:['title','body','target'],users:['status','role','department','site']}[t]||[];if(t==='users'&&req.user.role!=='owner')return res.status(403).json({error:'Owner only'});const keys=allowed.filter(k=>req.body[k]!==undefined);if(!keys.length)return res.status(400).json({error:'No changes'});const vals=keys.map(k=>req.body[k]);db.prepare(`UPDATE ${t} SET ${keys.map(k=>k+'=?').join(',')} WHERE id=?`).run(...vals,req.params.id);audit(req.user.username,'update',t,req.params.id);res.json({ok:true})});
app.post('/api/users',auth,(req,res)=>{if(req.user.role!=='owner')return res.status(403).json({error:'Owner only'});const {employee_no,username,name,password,role='employee',department='',site='ALL'}=req.body;if(!username||!password||!name)return res.status(400).json({error:'Missing fields'});try{const h=bcrypt.hashSync(password,10);const r=db.prepare('INSERT INTO users(employee_no,username,name,password_hash,role,department,site) VALUES(?,?,?,?,?,?,?)').run(employee_no||username,username,name,h,role,department,site);audit(req.user.username,'create','user',r.lastInsertRowid);res.json({id:r.lastInsertRowid})}catch(e){res.status(400).json({error:e.message})}});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.listen(process.env.PORT||3000,()=>console.log('SAVOURY running on http://localhost:'+(process.env.PORT||3000)));
